36 allow helix index changing in batch
UC-Davis-molecular-computing/scadnano pull request #784
Opened 2022-07-22 05:52 UTC by vbKenobi

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-07-22 14:00 UTC, dave-doty commented
Can you fill in a bit under each heading of the PR?

2022-07-22 23:32 UTC, vbKenobi commented
Should be updated!

2022-07-27 00:07 UTC, dave-doty requested changes

2022-08-07 00:12 UTC, dave-doty requested changes

2022-08-07 00:12 UTC, dave-doty commented on lib/src/middleware/helix_idxs_change.dart
> +          var msg = 'First duplicate found for helix ${old_index} with new index ${new_index}. ';
Sorry, try it one more time:

![image](https://user-images.githubusercontent.com/19274365/183269693-3792310d-fe6d-4a45-a441-ee3bcdd4e282.png)

Imagine you're a user and there's a HUGE list of indices there. If they tried to assign index a to b and also index c to b, then they'll want to know all three of a, b, c. The current error message is only telling them two of these.

Try this error message: "You tried to assign helices 4 and 5 both to 0. Each helix must have a *unique* new index; make sure all the integers you write are distinct from each other and do not appear elsewhere in the design."

2022-08-22 00:25 UTC, dave-doty requested changes
Something is still not right. I try this invalid change:

![image](https://user-images.githubusercontent.com/19274365/185817823-72e2b518-f5d2-40cd-87a2-94769d4f0be3.png)

It gives this error message:

![image](https://user-images.githubusercontent.com/19274365/185817835-43a8e0ac-475c-4b16-ba58-b7db251a8b7d.png)

It should instead say "*You tried assigning existing helices 0 and 1 to 0*" In other words it should indicate both "source" indices that are in conflict. Otherwise the user cannot locate the conflict and fix it if they only know one of the helices causing the problem.

2022-08-22 13:40 UTC, dave-doty approved these changes

2022-08-22 18:17 UTC, merged